# Generated by Django 4.0.6 on 2022-08-01 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ('id', 'task')},
        ),
    ]
