# Generated by Django 4.0.6 on 2022-08-01 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0003_alter_todolist_options_todolist_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={},
        ),
    ]
